[package]
name = "goatns"
description = "Yet another authoritative DNS name server. But with goat references."
version = "0.2.1"
edition = "2021"
rust-version = "1.64"
license = "MIT"
repository = "https://github.com/yaleman/goatns.git"
keywords = ["dns","server","tokio","api","oauth2","oidc"]
categories = ["network-programming"]


[workspace]
members = [
    ".",
    "axum-csp",
    "goatns-macros",
]

[lib]
bench=false

[profile.release]
lto = "fat"
opt-level = 3

[dependencies]
argon2 = "0.4"
askama = { version="0.11.1"}
async-sqlx-session = { git="https://github.com/jbr/async-sqlx-session.git", rev="3f2e1cf", default-features = false, features = ["sqlite"] }
async-trait = "0.1.62"
axum = { version="0.6.3", features=["http2", "headers", "original-uri", "macros"] }
axum-csp = { version="^0.0.1", path="axum-csp/"}
axum-extra = { version = "0.4.2", features = ["spa"] }
axum-macros = "0.3.2"
axum-server = { version = "0.4.3", features = [ "tls-rustls"] }
axum-sessions = "0.4.1"
bit-vec = "0.6.3"
bytes = "1.3.0"
chrono = { version = "0.4.23", features = ["clock"] }
clap = { version="4.1.1", features=["cargo"]}
concread = "0.4.0"
config = { version = "0.13", features = ["json"] }
dialoguer = "0.10.3"
enum-iterator = "1.2.0"
flexi_logger = { version = "0.24", features = ["async", "default"] }
futures = "0.3.25"
futures-util = "0.3.25"
gethostname = "0.4.1"
goatns-macros = { path = "./goatns-macros"}
hex = "0.4.3"
http = "0.2.8"
ipnet = { version = "2.7.1", features = [ "json", "serde" ] }
json5 = "0.4.1"
lazy_static = "1.4.0"
log = "0.4.17"
num-traits = "0.2.15"
oauth2 = "4.3.0"
openidconnect = "2.4.0"
packed_struct = { version = "0.10.1", features = ["byte_types_256"] }
rand = "0.8.5"
rand_core = { version = "0.6", features = ["std"] }
regex = "1.7.1"
reqwest = { version = "0.11.14", features = ["blocking", "cookies", "json", "rustls-tls"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_bytes = "0.11.8"
serde_derive = "1.0.145"
serde_json = "1.0.91"
sha2 = { version = "0.10.6", features = ["asm", "asm-aarch64"] }
shellexpand = "3.0.0"
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "sqlite", "json"], default-features=false }
tokio = { version = "1.25.0", features = ["full", "tracing"] }
tokio-cron-scheduler = "0.9.3"
tokio-stream = { version = "0.1.11", features = ["net"] }
tokio-util = { version = "0.7.4", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.3.5", features = ["trace","add-extension","compression-gzip"] }
tracing = "0.1.37"
url = { version = "2.3.1", features = ["serde"] }

[workspace.dependencies]

quote = "0.4"
proc-macro2 = "1.0.50"
syn = "1.0.107"

[dev-dependencies]
console-subscriber = "0.1.8"
criterion = "^0.4"
scopeguard = "1.1.0"
tracing-subscriber = "0.3.16"
trust-dns-resolver = { version = "0.22.0", features=["tokio", "tokio-runtime"] }

[[bench]]
name = "baselines"
harness = false

[[bench]]
name = "datastore"
harness = false

[[bench]]
name = "parsers"
harness = false

[build-dependencies]
syn.workspace = true
