[package]
name = "goatns"
description = "Yet another authoritative DNS name server. But with goat references."
version = "0.4.0"
edition = "2021"
rust-version = "1.70"
license = "MIT"
repository = "https://github.com/yaleman/goatns.git"
keywords = ["dns", "server", "tokio", "api", "oauth2", "oidc"]
categories = ["network-programming"]
include = [
    "src/**/*",
    "LICENSE.md",
    "README.md",
    "!**/*_test.*",
    "!**/tests/**/*",
]


[features]
default = []
otel = []

[workspace]
members = [".", "axum-csp", "goatns-macros"]

[lib]
bench = false

[profile.release]
lto = "fat"
opt-level = 3

[dependencies]
argon2 = "0.5"
askama = { version = "0.12.1" }
async-trait = "0.1.74"
axum = { version = "0.6.20", features = [
    "http2",
    "headers",
    "original-uri",
    "macros",
] }
axum-csp = { version = "^0.0.1", path = "axum-csp/" }
axum-extra = { version = "0.9.0" }
axum-macros = "0.3.8"
axum-server = { version = "0.5.1", features = ["tls-rustls"] }
axum-tracing-opentelemetry = { version = "0.11.0", features = [
    "tracing_subscriber_ext",
] }
base64 = "0.21.5"
bit-vec = "0.6.3"
bytes = "1.5.0"
chrono = { version = "0.4.31", features = ["clock"] }
clap = { version = "4.4.10", features = ["cargo"] }
concread = "0.4.3"
config = { version = "0.13", features = ["json"] }
dialoguer = "0.11.0"
enum-iterator = "1.4.1"
flexi_logger = { version = "0.27", features = ["async", "default"] }
futures = "0.3.29"
futures-util = "0.3.28"
gethostname = "0.4.3"
goatns-macros = { path = "./goatns-macros" }
hex = "0.4.3"
http = "0.2.10"
ipnet = { version = "2.9.0", features = ["json", "serde"] }
json5 = "0.4.1"
lazy_static = "1.4.0"
log = "0.4.20"
num-traits = "0.2.17"
oauth2 = "4.4.2"
openidconnect = "3.4.0"
opentelemetry-otlp = { version = "0.14.0", features = ["http-proto"] }
packed_struct = { version = "0.10.1", features = ["byte_types_256"] }
rand = "0.8.5"
rand_core = { version = "0.6", features = ["std"] }
regex = "1.10.2"
reqwest = { version = "0.11.22", features = [
    "blocking",
    "cookies",
    "json",
    "rustls-tls",
] }
rmp-serde = "1.1.2"
serde = { version = "1.0.193", features = ["derive"] }
serde_bytes = "0.11.12"
serde_derive = "1.0.145"
serde_json = "1.0.108"
sha2 = { version = "0.10.8", features = ["asm", "asm-aarch64"] }
shellexpand = "3.1.0"
sqlx = { version = "0.7.3", features = [
    "runtime-tokio-rustls",
    "sqlite",
    "json",
    "time",
    "uuid",
], default-features = false }
thiserror = "1.0.50"
time = "0.3.30"
tokio = { version = "1.34.0", features = ["full", "tracing"] }
tokio-cron-scheduler = "0.9.3"
tokio-stream = { version = "0.1.14", features = ["net"] }
tokio-util = { version = "0.7.10", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.4.4", features = [
    "fs",
    "trace",
    "add-extension",
    "compression-gzip",
] }
tower-sessions = { version = "0.6.0", features = [
    "sqlite-store",
    "deletion-task",
    "axum-core",
] }
tracing = "^0.1.40"
url = { version = "2.4.0", features = ["serde"] }


[workspace.dependencies]
proc-macro2 = "1.0.69"
syn = "2.0.39"

[dev-dependencies]
console-subscriber = "0.2.0"
criterion = "^0.5"
scopeguard = "1.2.0"
tracing-subscriber = "0.3.18"
trust-dns-resolver = { version = "0.23.2", features = [
    "tokio",
    "tokio-runtime",
] }

[[bench]]
name = "baselines"
harness = false

[[bench]]
name = "datastore"
harness = false

[[bench]]
name = "parsers"
harness = false

[build-dependencies]
syn = { workspace = true }
