[package]
name = "goatns"
version = "0.1.5"
edition = "2021"
rust-version = "1.64"

[lib]
bench=false

[profile.release]
lto = "thin"
opt-level = 3

[dependencies]
askama = { version="0.11.1"}
async-trait = "0.1.58"
axum = { version="0.5.17", features=["http2", "headers"] }
axum-extra = { version = "0.3.7", features = ["spa"] }
axum-macros = "0.2.3"
axum-server = { version = "0.4.3", features = [ "tls-rustls"] }
bit-vec = "0.6.3"
bytes = "1.2.1"
chrono = { version = "0.4.22", features = ["clock"] }
clap = { version="4.0.19", features=["cargo"]}
config = { version = "0.13", features = ["json"] }
enum-iterator = "1.2.0"
flexi_logger = { version = "0.24", features = ["async", "default"] }
gethostname = "0.4.0"
ipnet = { version = "2.5.0", features = [ "json", "serde" ] }
json5 = "0.4.1"
kanidm_proto = { version = "^1.1.0-alpha.10", git = "https://github.com/kanidm/kanidm.git" }
lazy_static = "1.4.0"
log = "0.4.17"
num-traits = "0.2.15"
packed_struct = { version = "0.10.0", features = ["byte_types_256"] }
rand = "0.8.5"
regex = "1.6.0"
reqwest = { version = "0.11.12", features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_bytes = "0.11.7"
serde_derive = "1.0.145"
serde_json = "1.0.86"
shellexpand = "2.1.2"
sqlx = { version = "0.6", features = [ "runtime-tokio-native-tls" , "sqlite" ] }
sqlx-core = { version = "0.6.2", features = ["runtime-tokio-native-tls", "sqlite"] }
tokio = { version = "1.21.2", features = ["full"] }
tokio-stream = { version = "0.1.11", features = ["net"] }
tokio-util = { version = "0.7.4", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["trace","add-extension"] }
tracing = "0.1.37"
url = { version = "2.3.1", features = ["serde"] }



[dev-dependencies]
criterion = "^0.4"
scopeguard = "1.1.0"
trust-dns-resolver = "0.22.0"

[[bench]]
name = "baselines"
harness = false

[[bench]]
name = "datastore"
harness = false

[[bench]]
name = "parsers"
harness = false
