[package]
name = "goatns"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
bit-vec = "0.6.3"
bytes = "1.2.1"
chrono = "0.4.22"
config = { version = "0.13", features = ["json"] }
femme = "2.2.1"
json5 = "0.4.1"
lazy_static = "1.4.0"
log = "0.4.17"
packed_struct = { version = "0.10.0", features = ["byte_types_256"] }
patricia_tree = "0.3.2"
serde = { version = "1.0.145", features = ["derive"] }
serde_bytes = "0.11.7"
shellexpand = "2.1.2"
tokio = { version = "1.21.2", features = ["full"] }
tokio-stream = { version = "0.1.10", features = ["net"] }
tokio-util = { version = "0.7.4", features = ["full"] }
