[package]
name = "goatns"
version = "0.1.4"
edition = "2021"
rust-version = "1.64"

[lib]
bench=false

[profile.release]
lto = "thin"
opt-level = 3

[dependencies]
bit-vec = "0.6.3"
bytes = "1.2.1"
chrono = "0.4.22"
clap = { version="4.0.19", features=["cargo"]}
config = { version = "0.13", features = ["json"] }
json5 = "0.4.1"
lazy_static = "1.4.0"
log = "0.4.17"
num-traits = "0.2.15"
packed_struct = { version = "0.10.0", features = ["byte_types_256"] }
patricia_tree = "0.3.2"
flexi_logger = { version = "0.24", features = ["async", "default"] }
regex = "1.6.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_bytes = "0.11.7"
serde_derive = "1.0.145"
serde_json = "1.0.86"
shellexpand = "2.1.2"
sqlx = { version = "0.6", features = [ "runtime-tokio-native-tls" , "sqlite" ] }
sqlx-core = { version = "0.6.2", features = ["runtime-tokio-native-tls", "sqlite"] }
tokio = { version = "1.21.2", features = ["full"] }
tokio-stream = { version = "0.1.11", features = ["net"] }
tokio-util = { version = "0.7.4", features = ["full"] }
tide = "0.16.0"
tide-rustls = "0.3.0"
driftwood = "0.0.6"
async-trait = "0.1.58"

[dev-dependencies]
criterion = "^0.4"
rand = "0.8.5"
trust-dns-resolver = "0.22.0"

[[bench]]
name = "baselines"
harness = false

[[bench]]
name = "datastore"
harness = false

[[bench]]
name = "parsers"
harness = false
