[package]
name = "goatns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6.3"
bytes = "1.2.1"
packed_struct = { version = "0.10.0", features = ["byte_types_256"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
tokio = { version = "1.21.1", features = ["full"] }
tokio-stream = { version = "0.1.10", features = ["net"] }
tokio-util = { version = "0.7.4", features = ["full"] }
