[package]
name = "goatns"
version = "0.4.0"
categories = ["network-programming"]
edition = "2021"
include = [
  "src/**/*",
  "LICENSE.md",
  "README.md",
  "!**/*_test.*",
  "!**/tests/**/*",
]
keywords = ["dns", "server", "tokio", "api", "oauth2", "oidc"]
license = "MIT"
repository = "https://github.com/yaleman/goatns.git"
rust-version = "1.70"
description = "Yet another authoritative DNS name server. But with goat references."

[features]
default = []
otel = []

[workspace]
members = [".", "goat-lib", "goatns-macros"]

[lib]
bench = false

[profile.release]
lto = "fat"
opt-level = 3

[dependencies]
argon2 = "0.5"
askama = { version = "0.12.1" }
async-trait = "0.1.80"
axum = { workspace = true, features = ["http2", "original-uri", "macros"] }
axum-csp = { git = "https://github.com/yaleman/axum-csp/", rev = "cb55f3d" }
axum-extra = { version = "0.9.3" }
axum-server = { version = "^0.6.0", features = ["tls-rustls"] }
axum-tracing-opentelemetry = { version = "0.11.0", features = [
  "tracing_subscriber_ext",
] }
base64 = "0.22.1"
bit-vec = "0.6.3"
bytes = "1.6.0"
chrono = { version = "0.4.38", features = ["clock"] }
clap = { version = "4.5.8", features = ["cargo"] }
concread = "0.5.2"
config = { version = "0.14", features = ["json"] }
dialoguer = "0.11.0"
enum-iterator = "2.1.0"
flexi_logger = { version = "0.28", features = ["async", "default"] }
futures = "0.3.30"
futures-util = "0.3.30"
gethostname = "0.4.3"
goat-lib = { path = "goat-lib" }
goatns-macros = { path = "./goatns-macros" }
hex = "0.4.3"
ipnet = { version = "2.9.0", features = ["json", "serde"] }
json5 = "0.4.1"
lazy_static = "1.5.0"
log = "0.4.22"
num-traits = "0.2.19"
oauth2 = "4.4.2"
openidconnect = "3.4.0"
opentelemetry-otlp = { version = "0.16.0", features = ["http-proto"] }
packed_struct = { version = "0.10.1", features = ["byte_types_256"] }
rand = "0.8.5"
rand_core = { version = "0.6", features = ["std"] }
regex = "1.10.5"
reqwest = { version = "0.12.4", features = [
  "blocking",
  "cookies",
  "json",
  "rustls-tls",
] }
rmp-serde = "1.3.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_bytes = "0.11.15"
serde_derive = "1.0.145"
serde_json = "1.0.118"
sha2 = { version = "0.10.8", features = ["asm", "asm-aarch64"] }
shellexpand = "3.1.0"
sqlx = { version = "0.7.4", features = [
  "runtime-tokio-rustls",
  "sqlite",
  "json",
  "time",
  "uuid",
], default-features = false }
thiserror = "1.0.61"
time = "0.3.36"
tokio = { version = "1.38.0", features = ["full", "tracing"] }
tokio-cron-scheduler = "0.10.2"
tokio-stream = { version = "0.1.15", features = ["net"] }
tokio-util = { version = "0.7.11", features = ["full"] }
tower = "^0.4.13"
tower-http = { version = "^0.5.2", features = [
  "fs",
  "trace",
  "add-extension",
  "compression-gzip",
] }
tower-sessions = { version = "^0.9.1", features = [
  "sqlite-store",
  "deletion-task",
  "axum-core",
] }
tracing = "^0.1.40"
url = { version = "2.5.2", features = ["serde"] }
utoipa = "4.2.3"
utoipa-swagger-ui = { version = "7.1.0", features = ["axum"] }

[workspace.dependencies]
axum = "^0.7.5"
proc-macro2 = "1.0.86"
syn = "2.0.68"

[dev-dependencies]
console-subscriber = "0.3.0"
criterion = "^0.5"
scopeguard = "1.2.0"
tracing-subscriber = "0.3.18"
trust-dns-resolver = { version = "0.23.2", features = [
  "tokio",
  "tokio-runtime",
] }

[[bench]]
name = "baselines"
harness = false

[[bench]]
name = "datastore"
harness = false

[[bench]]
name = "parsers"
harness = false

[build-dependencies]
syn = { workspace = true }
