[package]
name = "goatns"
version = "0.1.3"
edition = "2021"

[profile.release]
lto = "thin"
opt-level = 3

[dependencies]
bit-vec = "0.6.3"
bytes = "1.2.1"
chrono = "0.4.22"
clap = { version="4.0.18", features=["cargo"]}
config = { version = "0.13", features = ["json"] }
diesel = { version = "2.0.2", default-features = false, features=["sqlite", "serde_json"] }
femme = "2.2.1"
json5 = "0.4.1"
lazy_static = "1.4.0"
log = "0.4.17"
packed_struct = { version = "0.10.0", features = ["byte_types_256"] }
patricia_tree = "0.3.2"
serde = { version = "1.0.145", features = ["derive"] }
serde_bytes = "0.11.7"
serde_derive = "1.0.145"
serde_json = "1.0.86"
shellexpand = "2.1.2"
tokio = { version = "1.21.2", features = ["full"] }
tokio-stream = { version = "0.1.11", features = ["net"] }
tokio-util = { version = "0.7.4", features = ["full"] }

[dev-dependencies]
criterion = "^0.4"
trust-dns-resolver = "0.22.0"

[[bench]]
name = "baselines"
harness = false

[[bench]]
name = "datastore"
harness = false
