---
# you should customize this for your own needs, but it's kinda useful as-is
#
version: "3.9"
services:
  goatns:
    security_opt:
      - no-new-privileges:true
    read_only: true
    image: ghcr.io/yaleman/goatns:latest
    build:
      dockerfile: Dockerfile
      context: .
    init: true
    ports:
      - "15353:15353/udp"
      - "15353:15353/tcp"
      - "9000:9000/tcp"
    volumes:
      - type: "bind"
        source: "goatns.json"
        target: "/goatns.json"
        read_only: true
        bind:
          create_host_path: false
      - type: "bind"
        source: "zones.json"
        target: "/zones.json"
        read_only: true
        bind:
          create_host_path: false
      - type: "bind"
        source: "./db/"
        target: "/db/"
        read_only: false
        bind:
          create_host_path: true
