FROM gcr.io/distroless/cc as goatns
# # ======================
# https://github.com/GoogleContainerTools/distroless/blob/main/examples/rust/Dockerfile
COPY --from=builder /goatns/target/release/goatns /
ENV GOATNS_LOG_LEVEL=INFO

EXPOSE 15353/udp
EXPOSE 15353/tcp
WORKDIR /
USER nonroot
CMD ["./goatns"]
