[package]
name = "goatns-macros"
version = "0.0.1"
edition = "2021"
description = "Macros for the GoatNS Project"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "0.4"
proc-macro2 = "0.2.3"

