# REMOVE ALL THIS BEFORE YOU COMMIT
[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/yaleman/axum-csp/?rev=cb55f3d"]
git = "https://github.com/yaleman/axum-csp/"
rev = "cb55f3d"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
