//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sessions")]
#[allow(dead_code)] // because clippy and auto-generated code
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub data: Vec<u8>,
    pub expiry_date: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
#[allow(dead_code)] // because clippy and auto-generated code
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
