//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use chrono::Utc;
use sea_orm::entity::prelude::*;

use crate::error::GoatNsError;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_tokens")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: u64,
    pub name: String,
    pub issued: chrono::DateTime<Utc>,
    pub expiry: Option<chrono::DateTime<Utc>>,
    pub key: String,
    pub hash: String,
    pub userid: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::Userid",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Entity {
    pub(crate) async fn cleanup(db: &DatabaseConnection) -> Result<u64, GoatNsError> {
        let deleted = Self::delete_many()
            .filter(
                Column::Expiry
                    .is_not_null()
                    .and(Column::Expiry.lte(Utc::now().to_rfc3339())),
            )
            .exec(db)
            .await?;
        Ok(deleted.rows_affected)
    }
}
