//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::{
    ActiveValue::{NotSet, Set},
    entity::prelude::*,
};
use serde::{Deserialize, Serialize};

use crate::{
    enums::RecordClass, resourcerecord::InternalResourceRecord, web::api::filezonerecord::ZoneForm,
};

#[derive(Clone, Debug, DeriveEntityModel, Eq, Deserialize, Serialize)]
#[sea_orm(table_name = "zones")]
#[allow(dead_code)] // because clippy and auto-generated code
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, default = Uuid::now_v7())]
    pub id: Uuid,
    pub name: String,
    pub rname: String,
    pub serial: u32,
    pub refresh: u32,
    pub retry: u32,
    pub expire: u32,
    pub minimum: u32,
}

impl PartialEq for Model {
    fn eq(&self, other: &Self) -> bool {
        self.name == other.name
            && self.rname == other.rname
            && self.serial == other.serial
            && self.refresh == other.refresh
            && self.retry == other.retry
            && self.expire == other.expire
            && self.minimum == other.minimum
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ownership::Entity")]
    Ownership,
    #[sea_orm(has_many = "super::records::Entity")]
    Records,
}

impl Related<super::ownership::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ownership.def()
    }
}

impl Related<super::records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Records.def()
    }
}

impl Model {
    pub fn get_soa_record(&self, server_hostname: &str) -> InternalResourceRecord {
        InternalResourceRecord::SOA {
            zone: self.name.clone().into(),
            mname: server_hostname.into(),
            rname: self.rname.clone().into(),
            serial: self.serial,
            refresh: self.refresh,
            retry: self.retry,
            expire: self.expire,
            minimum: self.minimum,
            rclass: RecordClass::Internet,
        }
    }
}

impl From<ZoneForm> for ActiveModel {
    fn from(record: ZoneForm) -> Self {
        let mut res = ActiveModel {
            id: NotSet,
            name: Set(record.name),
            rname: Set(record.rname),
            serial: Set(record.serial),
            refresh: Set(record.refresh),
            retry: Set(record.retry),
            expire: Set(record.expire),
            minimum: Set(record.minimum),
        };

        if let Some(id) = record.id {
            res.id = sea_orm::ActiveValue::Set(id);
        };
        res
    }
}

impl ActiveModelBehavior for ActiveModel {
    fn new() -> Self {
        Self {
            id: Set(Uuid::now_v7()),
            ..ActiveModelTrait::default()
        }
    }
}
